version: '2'

services:
  webserver:
    build: ./
    image: neueda_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./document_root:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    command: --disable-partition-engine-check
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=neueda
      - MYSQL_DATABASE=neueda_challenge

volumes:
  db_data: {}

 